// Generated by CoffeeScript 1.10.0
var app, canvas_state, express, io, logger, path, stylus, user_actions, users;

express = require('express');

logger = require('morgan');

stylus = require('stylus');

path = require('path');

io = require('socket.io')();

app = express();

app.set('port', 3000);

app.set('view engine', 'jade');

app.use(logger('dev'));

app.use(stylus.middleware(path.join(__dirname, 'public')));

app.use(express["static"](path.join(__dirname, 'public')));

app.get('/', function(req, res) {
  return res.render('index');
});

io.listen(app.listen(app.get('port'), function() {
  return console.log('app is listening on http://localhost:' + app.get('port'));
}));

users = [];

user_actions = {};

canvas_state = void 0;

io.on('connect', function(socket) {
  console.log('connection');
  users.push(socket.id.substr(2));
  socket.emit('load canvas', {
    num_users: users.length,
    canvas_state: canvas_state,
    users: users
  });
  socket.broadcast.emit('user connected', {
    num_users: users.length,
    id: socket.id.substr(2)
  });
  socket.on('user move', function(pos) {
    pos.id = socket.id.substr(2);
    return socket.broadcast.emit('user move', pos);
  });
  socket.on('add path', function(path) {
    return socket.broadcast.emit('add path', path);
  });
  socket.on('remove path', function(path) {
    return socket.broadcast.emit('remove path', path);
  });
  socket.on('save canvas', function(canvas) {
    return canvas_state = canvas;
  });
  socket.on('save actions', function(actions) {
    return user_actions[socket.id] = actions;
  });
  socket.on('message', function(message) {
    return io.emit('new message', {
      id: socket.id.substr(2),
      message: message
    });
  });
  return socket.on('disconnect', function() {
    console.log('disconnection');
    console.log(user_actions[socket.id]);
    users.splice(users.indexOf(socket.id), 1);
    socket.broadcast.emit('user disconnected', {
      num_users: users.length,
      id: socket.id.substr(2),
      actions: user_actions[socket.id]
    });
    if (users.length === 0) {
      return canvas_state = void 0;
    }
  });
});
