// Generated by CoffeeScript 1.10.0
var app, canvas_state, express, io, logger, path, stylus, users;

express = require('express');

logger = require('morgan');

stylus = require('stylus');

path = require('path');

io = require('socket.io')();

app = express();

app.set('port', 3000);

app.set('view engine', 'jade');

app.use(logger('dev'));

app.use(stylus.middleware(path.join(__dirname, 'public')));

app.use(express["static"](path.join(__dirname, 'public')));

app.get('/', function(req, res) {
  return res.render('index');
});

io.listen(app.listen(app.get('port'), function() {
  return console.log('app is listening on http://localhost:' + app.get('port'));
}));

users = [];

canvas_state = void 0;

io.on('connect', function(socket) {
  users.push(socket.id);
  socket.emit('current state', {
    num_users: users.length,
    canvas: canvas_state
  });
  socket.broadcast.emit('user connected', {
    total: users.length,
    id: socket.id
  });
  socket.on('add path', function(path) {
    return socket.broadcast.emit('add path', path);
  });
  socket.on('save canvas', function(canvas) {
    return canvas_state = canvas;
  });
  return socket.on('disconnect', function() {
    users.splice(users.indexOf(socket.id), 1);
    return socket.broadcast.emit('user disconnected', {
      total: users.length,
      id: socket.id
    });
  });
});
